{% set version = "1.0" %}

package:
  name: mkdocs-bootstrap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs-bootstrap/mkdocs-bootstrap-{{ version }}.tar.gz
  sha256: 7efc2e12dd8b3a658cdfc58a31f10103f69abffa77369e9ea62ea325eb6eb0d8

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mkdocs_bootstrap

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  summary: 'Bootstrap theme for MkDocs'

extra:
  recipe-maintainers:
    - ocefpaf
