travis:
  secure:
    BINSTAR_TOKEN: Y//w/XJyNkt+JpOMfOQ5LIXdLkHxv8ijunZEI5z79gozVZmHgrbWEISCm0VGOkjS4xoyqdYJzPBt2wbHU50rCpHAVQGaVlrhalyuXzgMiuCUALd1/TLHH/HqhS3b55afQABgl1jqQfAgVqtVB8oc/LtdnBCr7eYqH7SViqAVvhSs/Y0gFDs8IVeq4s3GG4nF8yKLCIxnOknrNpxpWQgv8bjn7p0OqZRoLJ+aLSEcMt08HbObb/TymQ+blxEDo6kkdF8uTujqA4ntjhtd+9F9ZQrBP9+yQ9bA45wwgwJe+LIcv2YXMWBkCaa0T5Nfs5yIFcktiBM1k5qN23R//CSn5h1cEl/BovQbFd+qrKmafFPrIqE6iOIgQLN9Yk8nC6jPB5+hYAWT+alQLD44GyMEHDuGNfsU8VkXzK9YVQPtehPS3YxznmXpZeADCwp8sOhBR4roTcWfXhKW8jPNmYVtGojP/xBZKgjZ8AgmFmcIE9e/mX9NDDhCkdP0CVAMWElU584KRFhzHwCVKG/ViKnMihwUTqGsSGclznXHjvKIbjgp9uu4nCIkd9q1va5ksDTYtWKR2vXoKowrPNTboPJQFvnh6aVBV0MUnKxFLZu1v1/zGz5h1mTaWF62RPHZk7uMKEFcywtadReb95ts8V42iA8OzZK5/yS9F0KaoRc7D50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
